### ISSUE TITLE
Add an option to disallow the usage of default logger

### ISSUE THREAD

**Issue by AlekSi** [go-simpler/sloglint#30]
So, for example, `slog.Info` would be forbidden, but `l := slog.New(…); l.Info` would be allowed.

**Comment by tmzane** [comment]
Good idea!

I think disallowing global loggers in general might be a useful option, so we could implement it as something like `no-global: all` (forbid global loggers) and `no-global: default` (forbid the default logger). WDYT?

**Comment by AlekSi** [comment]
Sounds great!

**Comment by tmzane** [comment]
@AlekSi Implemented as discussed. Will probably land in the next `golangci-lint` release 👀
